language: elixir

elixir:
  - 1.6

services:
  - postgresql

before_script:
  - mix do ecto.create, ecto.migrate

script:
  - mix format --check-formatted && mix test

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master

